name: Setup Swift environment
description: Setup a Swift environment on Ubuntu or macOS 
author: Frederik Wallner
inputs:
  swift-version: 
    description: Swift version to configure
    required: true
    default: '5.1.1'
runs:
  using: node12
  main: lib/main.js
branding:
  icon: 'command'  
  color: 'orange'
