name: Build

on:
  push:
    branches:
    - master

jobs:
  build-dist:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - run: npm install
    - run: npm run pack-source-map

    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        file_pattern: dist/index.js
        commit_message: New dist
