name: CI

on: [push]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        swift: ["4.2.4"]
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        swift-version: ${{ matrix.swift }}
        os: ${{ matrix.os }}
    - name: Swift version
      run: echo $PATH && swift --version
