name: CI

on: [push]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        swift: ["4.2.4"]
    steps:
    - uses: actions/checkout@master
    - uses: fwal/setup-swift@master
      with:
        swift-version: ${{ matrix.swift }}
    - name: Swift version
      run: swift --version
