name: Tests

on: [push]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run format-check
    - run: npm test
  integration-test:
    name: Integrate Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.2.1", "4.2.4"]
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run build && npm run pack
    - uses: ./
      with:
        swift-version: ${{ matrix.swift }}
    - name: Swift version
      run: swift --version | grep ${{ matrix.swift }} || echo "Swift version mismatch after run!" && exit 1
