name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Release Draft
        id: release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set version
        run: npm version ${{ steps.release_draft.outputs.name }} --allow-same-version true --git-tag-version false

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run all

      - name: Commit 
        uses: EndBug/add-and-commit@v8
      
